export const APPROVE_PRODUCT = 'APPROVE_PRODUCT';
export const MARK_MISSING = 'MARK_MISSING';
export const OPEN_EDIT_POPUP = 'OPEN_EDIT_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const PRODUCT_REQUEST="PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const PRODUCT_FAILURE="PRODUCT_FAILURE";
